title: yshrsmz.github.io
description: Thoughts, stories and ideas
remote_theme: Sylhare/Type-on-Strap
url: https://yshrsmz.github.io
permalink: /:year/:month/:day/:title/

author:
  author: Yasuhiro Shimizu
  url: https://twitter.com/_yshrsmz

paginate: 10
paginate_path: "page:num"

sidebar_home_link:  true

disqus:
  shortname: yshrsmz-github-io

theme_settings:
  # meta
  title: Theoretical Cat
  description: Thoughts, stories and ideas
  gravatar: 9e8f6ad3eaaca7e727dd2b9ae84cd894

  # header/footer
  header_text: >
    <p>Thoughts, stories and ideas</p>
  header_text_feature_image: assets/img/dactyl.jpeg
  footer_text: Copyright 2018

  # icons
  rss: true
  email_address: the.phantom.bane+blog@gmail.com
  linkedin: https://www.linkedin.com/in/yshrsmz/
  stack_exchange: https://stackexchange.com/users/456702/yshrsmz
  github: yshrsmz
  twitter: _yshrsmz

  # scripts/features
  disqus_shortname: yshrsmz-github-io
  search: false
  tags: true

plugins:
  - jekyll-feed
