title: CodingFeline
description: Thoughts, stories and ideas
remote_theme: Sylhare/Type-on-Strap
url: https://www.yslibrary.net
permalink: /:year/:month/:day/:title/

paginate: 10
paginate_path: "page:num"

sidebar_home_link:  true

## THEME-SPECIFIC CONFIGURATION
# meta
title: CodingFeline
avatar: assets/img/logo.png
description: Thoughts, stories and ideas
gravatar: 9e8f6ad3eaaca7e727dd2b9ae84cd894

# header/footer
header_text: >
  <p>Thoughts, stories and ideas</p>
header_feature_image: assets/img/dactyl.jpeg
footer_text: Copyright 2019

# scripts/features
google_analytics: UA-61198465-1
disqus_shortname: yslibrary


plugins:
  - jekyll-feed
